### ISSUE TITLE
Kubernetes interoperability

### ISSUE THREAD

**Issue by yurmix** [dbos-inc/dbos-demo-apps#115]
This is an enticing idea, but you're 10 years late to the "data center OS" game.
Due to the fact that Kubernetes has de facto won that game and has the monopoly in the field, I would suggest you develop a Kubernetes-interoperable API (Or an automated code migration tool) which will let existing clusters/apps migrate from Kubernetes to DBOS.

**Comment by kraftp** [comment]
We're thinking about this (and the broader migration question), but it's a long-term project
